name: linters
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Lint the codebase
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_MARKDOWN: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LINTER_RULES_PATH: /
        MARKDOWN_CONFIG_FILE: .markdownlint.json
        FILTER_REGEX_EXCLUDE: CHANGELOG.md